// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0-devel
// 	protoc        v3.20.1
// source: pb_login.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//心跳包
type MHeartBitTos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time *int32 `protobuf:"varint,1,opt,name=time,proto3,oneof" json:"time,omitempty"`
}

func (x *MHeartBitTos) Reset() {
	*x = MHeartBitTos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_login_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MHeartBitTos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MHeartBitTos) ProtoMessage() {}

func (x *MHeartBitTos) ProtoReflect() protoreflect.Message {
	mi := &file_pb_login_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MHeartBitTos.ProtoReflect.Descriptor instead.
func (*MHeartBitTos) Descriptor() ([]byte, []int) {
	return file_pb_login_proto_rawDescGZIP(), []int{0}
}

func (x *MHeartBitTos) GetTime() int32 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

// 发给客户端
type MHeartBitToc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time *int32 `protobuf:"varint,1,opt,name=time,proto3,oneof" json:"time,omitempty"`
}

func (x *MHeartBitToc) Reset() {
	*x = MHeartBitToc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_login_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MHeartBitToc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MHeartBitToc) ProtoMessage() {}

func (x *MHeartBitToc) ProtoReflect() protoreflect.Message {
	mi := &file_pb_login_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MHeartBitToc.ProtoReflect.Descriptor instead.
func (*MHeartBitToc) Descriptor() ([]byte, []int) {
	return file_pb_login_proto_rawDescGZIP(), []int{1}
}

func (x *MHeartBitToc) GetTime() int32 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

var File_pb_login_proto protoreflect.FileDescriptor

var file_pb_login_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x62, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x22, 0x33, 0x0a, 0x0f, 0x6d, 0x5f, 0x68, 0x65, 0x61,
	0x72, 0x74, 0x5f, 0x62, 0x69, 0x74, 0x5f, 0x74, 0x6f, 0x73, 0x12, 0x17, 0x0a, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x33, 0x0a, 0x0f,
	0x6d, 0x5f, 0x68, 0x65, 0x61, 0x72, 0x74, 0x5f, 0x62, 0x69, 0x74, 0x5f, 0x74, 0x6f, 0x63, 0x12,
	0x17, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pb_login_proto_rawDescOnce sync.Once
	file_pb_login_proto_rawDescData = file_pb_login_proto_rawDesc
)

func file_pb_login_proto_rawDescGZIP() []byte {
	file_pb_login_proto_rawDescOnce.Do(func() {
		file_pb_login_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_login_proto_rawDescData)
	})
	return file_pb_login_proto_rawDescData
}

var file_pb_login_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_login_proto_goTypes = []interface{}{
	(*MHeartBitTos)(nil), // 0: login.m_heart_bit_tos
	(*MHeartBitToc)(nil), // 1: login.m_heart_bit_toc
}
var file_pb_login_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_login_proto_init() }
func file_pb_login_proto_init() {
	if File_pb_login_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_login_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MHeartBitTos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_login_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MHeartBitToc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pb_login_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_pb_login_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_login_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_login_proto_goTypes,
		DependencyIndexes: file_pb_login_proto_depIdxs,
		MessageInfos:      file_pb_login_proto_msgTypes,
	}.Build()
	File_pb_login_proto = out.File
	file_pb_login_proto_rawDesc = nil
	file_pb_login_proto_goTypes = nil
	file_pb_login_proto_depIdxs = nil
}
