//  protoc --go_out=. --go_opt=paths=source_relative game.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.4
// source: game.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//   下發給客戶端的游戲信息
type GameEnterReplyToc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameSid   string `protobuf:"bytes,1,opt,name=game_sid,json=gameSid,proto3" json:"game_sid,omitempty"`        // 本局游戏唯一标志
	StartTime int64  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` //  游戲开始的时间
	EnterTime int64  `protobuf:"varint,3,opt,name=enter_time,json=enterTime,proto3" json:"enter_time,omitempty"` // 玩家進入游戲時間
}

func (x *GameEnterReplyToc) Reset() {
	*x = GameEnterReplyToc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameEnterReplyToc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEnterReplyToc) ProtoMessage() {}

func (x *GameEnterReplyToc) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEnterReplyToc.ProtoReflect.Descriptor instead.
func (*GameEnterReplyToc) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *GameEnterReplyToc) GetGameSid() string {
	if x != nil {
		return x.GameSid
	}
	return ""
}

func (x *GameEnterReplyToc) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GameEnterReplyToc) GetEnterTime() int64 {
	if x != nil {
		return x.EnterTime
	}
	return 0
}

// 下注用户定义
type BetUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName    string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`                  //  用戶名稱
	BetAccount  *int64   `protobuf:"varint,2,opt,name=bet_account,json=betAccount,proto3,oneof" json:"bet_account,omitempty"`     //  投注金額
	EscapePoint *float32 `protobuf:"fixed32,3,opt,name=escape_point,json=escapePoint,proto3,oneof" json:"escape_point,omitempty"` // 逃生點
	Reward      *float32 `protobuf:"fixed32,4,opt,name=reward,proto3,oneof" json:"reward,omitempty"`                              // 获得的奖励
	Ranker      *int64   `protobuf:"varint,5,opt,name=ranker,proto3,oneof" json:"ranker,omitempty"`                               // 投注的排名
}

func (x *BetUser) Reset() {
	*x = BetUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BetUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetUser) ProtoMessage() {}

func (x *BetUser) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetUser.ProtoReflect.Descriptor instead.
func (*BetUser) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *BetUser) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *BetUser) GetBetAccount() int64 {
	if x != nil && x.BetAccount != nil {
		return *x.BetAccount
	}
	return 0
}

func (x *BetUser) GetEscapePoint() float32 {
	if x != nil && x.EscapePoint != nil {
		return *x.EscapePoint
	}
	return 0
}

func (x *BetUser) GetReward() float32 {
	if x != nil && x.Reward != nil {
		return *x.Reward
	}
	return 0
}

func (x *BetUser) GetRanker() int64 {
	if x != nil && x.Ranker != nil {
		return *x.Ranker
	}
	return 0
}

//       上傳的投注信息
type BetUserTos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameSid     int64  `protobuf:"varint,1,opt,name=game_sid,json=gameSid,proto3" json:"game_sid,omitempty"`             //本局游戏唯一标志
	UserName    string `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`           //      用戶名稱
	BetAccount  int64  `protobuf:"varint,3,opt,name=bet_account,json=betAccount,proto3" json:"bet_account,omitempty"`    //      投注金額
	EscapePoint int64  `protobuf:"varint,4,opt,name=escape_point,json=escapePoint,proto3" json:"escape_point,omitempty"` //    自動逃生點
}

func (x *BetUserTos) Reset() {
	*x = BetUserTos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BetUserTos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetUserTos) ProtoMessage() {}

func (x *BetUserTos) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetUserTos.ProtoReflect.Descriptor instead.
func (*BetUserTos) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *BetUserTos) GetGameSid() int64 {
	if x != nil {
		return x.GameSid
	}
	return 0
}

func (x *BetUserTos) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *BetUserTos) GetBetAccount() int64 {
	if x != nil {
		return x.BetAccount
	}
	return 0
}

func (x *BetUserTos) GetEscapePoint() int64 {
	if x != nil {
		return x.EscapePoint
	}
	return 0
}

//       排名前10的投注信息
type Bet_10Toc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameSid  int64      `protobuf:"varint,1,opt,name=game_sid,json=gameSid,proto3" json:"game_sid,omitempty"`
	TenUsers []*BetUser `protobuf:"bytes,2,rep,name=ten_users,json=tenUsers,proto3" json:"ten_users,omitempty"` //当前前10名用户信息
}

func (x *Bet_10Toc) Reset() {
	*x = Bet_10Toc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bet_10Toc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bet_10Toc) ProtoMessage() {}

func (x *Bet_10Toc) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bet_10Toc.ProtoReflect.Descriptor instead.
func (*Bet_10Toc) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *Bet_10Toc) GetGameSid() int64 {
	if x != nil {
		return x.GameSid
	}
	return 0
}

func (x *Bet_10Toc) GetTenUsers() []*BetUser {
	if x != nil {
		return x.TenUsers
	}
	return nil
}

//         发送逃生点给服务器端
type EscapePointTos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameSid     int64  `protobuf:"varint,1,opt,name=game_sid,json=gameSid,proto3" json:"game_sid,omitempty"`             //本局游戏唯一标志
	UserName    string `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`           //      用戶名稱
	EscapePoint int64  `protobuf:"varint,3,opt,name=escape_point,json=escapePoint,proto3" json:"escape_point,omitempty"` //        逃生點
}

func (x *EscapePointTos) Reset() {
	*x = EscapePointTos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EscapePointTos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscapePointTos) ProtoMessage() {}

func (x *EscapePointTos) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscapePointTos.ProtoReflect.Descriptor instead.
func (*EscapePointTos) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *EscapePointTos) GetGameSid() int64 {
	if x != nil {
		return x.GameSid
	}
	return 0
}

func (x *EscapePointTos) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *EscapePointTos) GetEscapePoint() int64 {
	if x != nil {
		return x.EscapePoint
	}
	return 0
}

//         当前实况
type SituationToc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*BetUser `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *SituationToc) Reset() {
	*x = SituationToc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SituationToc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SituationToc) ProtoMessage() {}

func (x *SituationToc) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SituationToc.ProtoReflect.Descriptor instead.
func (*SituationToc) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *SituationToc) GetUsers() []*BetUser {
	if x != nil {
		return x.Users
	}
	return nil
}

//         发送爆点给客户端
type ExplosionToc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameSid   int64   `protobuf:"varint,1,opt,name=game_sid,json=gameSid,proto3" json:"game_sid,omitempty"` //本局游戏唯一标志
	Explosion float32 `protobuf:"fixed32,2,opt,name=explosion,proto3" json:"explosion,omitempty"`           //          爆点
}

func (x *ExplosionToc) Reset() {
	*x = ExplosionToc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExplosionToc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplosionToc) ProtoMessage() {}

func (x *ExplosionToc) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplosionToc.ProtoReflect.Descriptor instead.
func (*ExplosionToc) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *ExplosionToc) GetGameSid() int64 {
	if x != nil {
		return x.GameSid
	}
	return 0
}

func (x *ExplosionToc) GetExplosion() float32 {
	if x != nil {
		return x.Explosion
	}
	return 0
}

//发送过去100局的爆点给客户端
type Past_100ExplosionToc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameSid   int64   `protobuf:"varint,1,opt,name=game_sid,json=gameSid,proto3" json:"game_sid,omitempty"`   //本局游戏唯一标志
	Explosion float32 `protobuf:"fixed32,2,opt,name=explosion,proto3" json:"explosion,omitempty"`             //  爆点
	UserName  string  `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"` //极限逃生用戶名稱
	Height    float32 `protobuf:"fixed32,4,opt,name=height,proto3" json:"height,omitempty"`                   //极限逃生用戶高度
}

func (x *Past_100ExplosionToc) Reset() {
	*x = Past_100ExplosionToc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Past_100ExplosionToc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Past_100ExplosionToc) ProtoMessage() {}

func (x *Past_100ExplosionToc) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Past_100ExplosionToc.ProtoReflect.Descriptor instead.
func (*Past_100ExplosionToc) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *Past_100ExplosionToc) GetGameSid() int64 {
	if x != nil {
		return x.GameSid
	}
	return 0
}

func (x *Past_100ExplosionToc) GetExplosion() float32 {
	if x != nil {
		return x.Explosion
	}
	return 0
}

func (x *Past_100ExplosionToc) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Past_100ExplosionToc) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_game_proto protoreflect.FileDescriptor

var file_game_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6f, 0x0a, 0x14,
	0x67, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79,
	0x5f, 0x74, 0x6f, 0x63, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x69, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xe6, 0x01,
	0x0a, 0x08, 0x62, 0x65, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0b, 0x62, 0x65, 0x74, 0x5f, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x0a,
	0x62, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x12, 0x26, 0x0a,
	0x0c, 0x65, 0x73, 0x63, 0x61, 0x70, 0x65, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x48, 0x01, 0x52, 0x0b, 0x65, 0x73, 0x63, 0x61, 0x70, 0x65, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x02, 0x48, 0x02, 0x52, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x88,
	0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x72, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x48, 0x03, 0x52, 0x06, 0x72, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42,
	0x0e, 0x0a, 0x0c, 0x5f, 0x62, 0x65, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42,
	0x0f, 0x0a, 0x0d, 0x5f, 0x65, 0x73, 0x63, 0x61, 0x70, 0x65, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x5f,
	0x72, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x22, 0x8a, 0x01, 0x0a, 0x0c, 0x62, 0x65, 0x74, 0x5f, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x5f,
	0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x53,
	0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x62, 0x65, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x62, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x65, 0x73, 0x63, 0x61, 0x70, 0x65, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x65, 0x73, 0x63, 0x61, 0x70, 0x65, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x22, 0x4f, 0x0a, 0x0a, 0x62, 0x65, 0x74, 0x5f, 0x31, 0x30, 0x5f, 0x74, 0x6f,
	0x63, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x09,
	0x74, 0x65, 0x6e, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x62, 0x65, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x22, 0x6d, 0x0a, 0x10, 0x65, 0x73, 0x63, 0x61, 0x70, 0x65, 0x5f, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x74, 0x6f, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x61, 0x6d, 0x65,
	0x53, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x65, 0x73, 0x63, 0x61, 0x70, 0x65, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x65, 0x73, 0x63, 0x61, 0x70, 0x65, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x22, 0x30, 0x0a, 0x0d, 0x73, 0x69, 0x74, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x74, 0x6f, 0x63, 0x12, 0x1f, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x62, 0x65, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x52, 0x05,
	0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x48, 0x0a, 0x0d, 0x65, 0x78, 0x70, 0x6c, 0x6f, 0x73, 0x69,
	0x6f, 0x6e, 0x5f, 0x74, 0x6f, 0x63, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x69,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x6c, 0x6f, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x65, 0x78, 0x70, 0x6c, 0x6f, 0x73, 0x69, 0x6f, 0x6e, 0x22,
	0x86, 0x01, 0x0a, 0x16, 0x70, 0x61, 0x73, 0x74, 0x5f, 0x31, 0x30, 0x30, 0x5f, 0x65, 0x78, 0x70,
	0x6c, 0x6f, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x6f, 0x63, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x61,
	0x6d, 0x65, 0x5f, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x61,
	0x6d, 0x65, 0x53, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x6c, 0x6f, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x65, 0x78, 0x70, 0x6c, 0x6f, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData = file_game_proto_rawDesc
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_proto_rawDescData)
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_game_proto_goTypes = []interface{}{
	(*GameEnterReplyToc)(nil),    // 0: game_enter_reply_toc
	(*BetUser)(nil),              // 1: bet_user
	(*BetUserTos)(nil),           // 2: bet_user_tos
	(*Bet_10Toc)(nil),            // 3: bet_10_toc
	(*EscapePointTos)(nil),       // 4: escape_point_tos
	(*SituationToc)(nil),         // 5: situation_toc
	(*ExplosionToc)(nil),         // 6: explosion_toc
	(*Past_100ExplosionToc)(nil), // 7: past_100_explosion_toc
}
var file_game_proto_depIdxs = []int32{
	1, // 0: bet_10_toc.ten_users:type_name -> bet_user
	1, // 1: situation_toc.users:type_name -> bet_user
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameEnterReplyToc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BetUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BetUserTos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bet_10Toc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EscapePointTos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SituationToc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExplosionToc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Past_100ExplosionToc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_game_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_rawDesc = nil
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
