// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.4
// source: pb_stream.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamRequestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Msg      uint32 `protobuf:"varint,2,opt,name=msg,proto3" json:"msg,omitempty"`  // 消息编号
	Data     []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"` // 数据
}

func (x *StreamRequestData) Reset() {
	*x = StreamRequestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_stream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequestData) ProtoMessage() {}

func (x *StreamRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_pb_stream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequestData.ProtoReflect.Descriptor instead.
func (*StreamRequestData) Descriptor() ([]byte, []int) {
	return file_pb_stream_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequestData) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *StreamRequestData) GetMsg() uint32 {
	if x != nil {
		return x.Msg
	}
	return 0
}

func (x *StreamRequestData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type StreamResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string   `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`  //玩家长连接id
	BAllUser bool     `protobuf:"varint,2,opt,name=bAllUser,proto3" json:"bAllUser,omitempty"` //全服在线玩家广播
	Uids     []string `protobuf:"bytes,3,rep,name=uids,proto3" json:"uids,omitempty"`          //广播给指定玩家
	Msg      uint32   `protobuf:"varint,4,opt,name=msg,proto3" json:"msg,omitempty"`           // 消息编号
	Data     []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`          // 数据
}

func (x *StreamResponseData) Reset() {
	*x = StreamResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_stream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponseData) ProtoMessage() {}

func (x *StreamResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_pb_stream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponseData.ProtoReflect.Descriptor instead.
func (*StreamResponseData) Descriptor() ([]byte, []int) {
	return file_pb_stream_proto_rawDescGZIP(), []int{1}
}

func (x *StreamResponseData) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *StreamResponseData) GetBAllUser() bool {
	if x != nil {
		return x.BAllUser
	}
	return false
}

func (x *StreamResponseData) GetUids() []string {
	if x != nil {
		return x.Uids
	}
	return nil
}

func (x *StreamResponseData) GetMsg() uint32 {
	if x != nil {
		return x.Msg
	}
	return 0
}

func (x *StreamResponseData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pb_stream_proto protoreflect.FileDescriptor

var file_pb_stream_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x62, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x55, 0x0a, 0x11, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x86, 0x01, 0x0a, 0x12, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x62,
	0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x62,
	0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x75, 0x69, 0x64, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x32, 0x45, 0x0a, 0x0a, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x4d, 0x73, 0x67, 0x12,
	0x37, 0x0a, 0x08, 0x50, 0x50, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x12, 0x2e, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x1a,
	0x13, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x28, 0x01, 0x30, 0x01, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_stream_proto_rawDescOnce sync.Once
	file_pb_stream_proto_rawDescData = file_pb_stream_proto_rawDesc
)

func file_pb_stream_proto_rawDescGZIP() []byte {
	file_pb_stream_proto_rawDescOnce.Do(func() {
		file_pb_stream_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_stream_proto_rawDescData)
	})
	return file_pb_stream_proto_rawDescData
}

var file_pb_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_stream_proto_goTypes = []interface{}{
	(*StreamRequestData)(nil),  // 0: StreamRequestData
	(*StreamResponseData)(nil), // 1: StreamResponseData
}
var file_pb_stream_proto_depIdxs = []int32{
	0, // 0: ForwardMsg.PPStream:input_type -> StreamRequestData
	1, // 1: ForwardMsg.PPStream:output_type -> StreamResponseData
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_stream_proto_init() }
func file_pb_stream_proto_init() {
	if File_pb_stream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_stream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamRequestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_stream_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_stream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_stream_proto_goTypes,
		DependencyIndexes: file_pb_stream_proto_depIdxs,
		MessageInfos:      file_pb_stream_proto_msgTypes,
	}.Build()
	File_pb_stream_proto = out.File
	file_pb_stream_proto_rawDesc = nil
	file_pb_stream_proto_goTypes = nil
	file_pb_stream_proto_depIdxs = nil
}
